name: gym_mirror
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  path_provider: ^2.1.2
  intl: ^0.18.1
  collection: ^1.18.0
  flutter_bloc: ^8.1.4
  meta: ^1.10.0
  equatable: ^2.0.5
  get_it: ^7.6.7
  health: ^10.2.0

  #Cache dependencies
  flutter_cache_manager: ^3.3.1
  asset_cache: ^2.1.0
  shared_preferences: ^2.2.3
  
  #UI dependencies

  flutter_onboarding_slider: ^1.0.11
  auto_route: ^8.0.3
  another_flutter_splash_screen: ^1.2.0
  auto_size_text: ^3.0.0
  o3d: ^3.1.0
  percent_indicator: ^4.2.3
  numberpicker: ^2.1.2
  bottom_sheet: ^4.0.4
  syncfusion_flutter_charts: ^25.2.6
  permission_handler: ^11.3.1
  fl_chart: ^0.68.0
  multi_dropdown: ^2.1.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.1.7
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/background/
    - assets/fonts/
    - assets/models/
    - assets/icons/

  fonts:
    - family: Outer-Sans
      fonts:
        - asset: assets/fonts/Made-Outer-Sans/MADE-Outer-Sans-Bold.otf
        - asset: assets/fonts/Made-Outer-Sans/MADE-Outer-Sans-Light.otf
        - asset: assets/fonts/Made-Outer-Sans/MADE-Outer-Sans-Medium.otf
        - asset: assets/fonts/Made-Outer-Sans/MADE-Outer-Sans-Regular.otf
        - asset: assets/fonts/Made-Outer-Sans/MADE-Outer-Sans-Thin.otf
flutter_intl:
  enabled: true
